#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-phpsettings-update';

event_actions($event,
	'initialize-default-databases' => '00');
    templates2events("/etc/php.d/nethserver.ini", $event);
